/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./pages/AboutPage.vue')['default']
    ButtonContainer: typeof import('./../../white-label-vue/src/components/ButtonContainer.vue')['default']
    CardContainer: typeof import('./../../white-label-vue/src/components/CardContainer.vue')['default']
    ComponentsPage: typeof import('./../../white-label-vue/src/pages/ComponentsPage.vue')['default']
    IconContainer: typeof import('./../../white-label-vue/src/components/IconContainer.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    ProductsPage: typeof import('./../../white-label-vue/src/pages/ProductsPage.vue')['default']
    RatingContainer: typeof import('./../../white-label-vue/src/components/RatingContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
